### ISSUE TITLE
thanks for your summary

### ISSUE THREAD

**Issue by shoutOutYangJie** [MarkMoHR/Awesome-Edge-Detection-Papers#1]
it seems that semantic edge detection works are comparatively rare, cvpr2019 have just one work, isn't it?

**Comment by MarkMoHR** [comment]
hi @shoutOutYangJie ,
which one is the cvpr2019 paper about semantic edge detection? Would you please update it and create a pull request?

**Comment by shoutOutYangJie** [comment]
> hi @shoutOutYangJie ,
> which one is the cvpr2019 paper about semantic edge detection? Would you please update it and create a pull request?

I mean

**Comment by shoutOutYangJie** [comment]
> > hi @shoutOutYangJie ,
> > which one is the cvpr2019 paper about semantic edge detection? Would you please update it and create a pull request?

**Comment by shoutOutYangJie** [comment]
> hi @shoutOutYangJie ,
> which one is the cvpr2019 paper about semantic edge detection? Would you please update it and create a pull request?

I mean that "Bi-Directional Cascade Network for Perceptual Edge Detection" this paper is only one cvpr2019 for edge dection? what is difference between general edge dectection and semantic detection?
I think casenet is categories-aware semantic edge detection ,but for binary detection which can draw a semantic contour ,they are semantic edge detection

**Comment by MarkMoHR** [comment]
hi @shoutOutYangJie ,
*BDCN* is the only cvpr2019 paper about edge detection I have seen up till now. Maybe there are other papers which are not released now.

"General edge dectection", I mean, is binary detection which outputs a binary image.
"Semantic edge detection" is for categories-aware edge detection.

**Comment by shoutOutYangJie** [comment]
> hi @shoutOutYangJie ,
> _BDCN_ is the only cvpr2019 paper about edge detection I have seen up till now. Maybe there are other papers which are not released now.
> 
> "General edge dectection", I mean, is binary detection which outputs a binary image.
> "Semantic edge detection" is for categories-aware edge detection.

BDCN draws object contour without any other contours  on the intra-object. for example,  it draw a person contour, but don't draw contours of pattern of person's clothes. So BDCN' contour is semantic, because it knows a whole object semantic information. right?

**Comment by MarkMoHR** [comment]
hi @shoutOutYangJie ,
"semantic" generally means categories-aware, like *semantic segmentation*
