### ISSUE TITLE
do you know which algorithm is suitable for detecting the edge of the connection of the clothes shoulders and sleeves

### ISSUE THREAD

**Issue by ShaneYS** [MarkMoHR/Awesome-Edge-Detection-Papers#2]
hi Haoran , thanks for your repo about edge detection.
I want to detect the edge of the connection of the clothes shoulders and sleeves, and I have already tried some traditional algorithms such as canny and random forest. But not good because the color of shoulders and sleeves are similar.

Now I want to try some deep learning algorithms, but I know nothing about edge detection with DL, so can you tell me which algorithm is suitable for my task?

**Comment by MarkMoHR** [comment]
Hi @ShaneYS ,
emm... It seems that none of these approaches are designed for clothes edge. I think you can try the newest methods with code and models released listed in *General edge detection* and *Object contour detection*, to see which one is the best.

**Comment by ShaneYS** [comment]
> 
> 
> Hi @ShaneYS ,
> emm... It seems that none of these approaches are designed for clothes edge. I think you can try the newest methods with code and models released listed in _General edge detection_ and _Object contour detection_, to see which one is the best.

thanks for your reply. I will try BDCN first.
