### ISSUE TITLE
Edge PR curves

### ISSUE THREAD

**Issue by yun-liu** [MarkMoHR/Awesome-Edge-Detection-Papers#6]
Hi, @MarkMoHR 
I have created a GitHub repository to plot edge PR curves for many existing edge detectors at https://github.com/yun-liu/plot-edge-pr-curves. This repository is useful to edge research. Would you mind adding this url to this project?

**Comment by MarkMoHR** [comment]
Hi, @yun-liu 
done!

**Comment by yun-liu** [comment]
@MarkMoHR Thank you very much!
